spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      url: jdbc:mysql://175.178.164.43:3306/api-food
      username: api-food
      password: x76aKnY348EAz5hY
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false

